### ISSUE TITLE
You forgot to add a newline character here.

### ISSUE THREAD

**Issue by ghost** [iGio90/FridaAndroidInjector#3]
https://github.com/iGio90/FridaAndroidInjector/blob/f3a7f266f1d43dea82a1ca644053328498c1ad10/fridainjector/src/main/java/com/igio90/fridainjector/Utils.java#L59

**Comment by iGio90** [comment]
thanks!

https://github.com/iGio90/FridaAndroidInjector/commit/4e4cb659af45f1b35fa91246df6839c546ccdb8a
